In [1]:
import tensorflow as tf
import tsp_env
import numpy as np

In [7]:
env = tsp_env.TSP_env(3)
env.reset()

array([ 0.,  0.,  0.])

In [8]:
env.weight_matrix

array([[ 0.        ,  0.53126678,  0.14754819],
       [ 0.53126678,  0.        ,  0.67551077],
       [ 0.14754819,  0.67551077,  0.        ]])

In [9]:
env.step(0)

(array([ 1.,  0.,  0.]), 0, False)

In [10]:
env.compute_subtour_length()

0

In [11]:
env.step(1)

(array([ 1.,  1.,  0.]), -1.0625335654188435, False)

In [12]:
env.compute_subtour_length()

1.0625335654188435

In [14]:
env.step(2)

(array([ 1.,  1.,  1.]), -0.2917921770452534, True)

In [15]:
env.compute_subtour_length()

1.3543257424640969

In [16]:
1.3543257424640969 - 1.0625335654188435

0.2917921770452534

In [18]:
import mvc_env
env = mvc_env.MVC_env(7)

In [34]:
returns = []
for i in range(100):
    env.reset()
    best_return = -100
    for i in range(100):
        ret = env.at_random_solution()[0]
        if ret > best_return:
            best_return = ret
    returns.append(best_return)

In [35]:
np.mean(returns)

-2.0299999999999998

In [27]:
returns

[-2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0,
 -2.0]